# fastapi
import traceback
from fastapi import FastAPI

# utils import
from api.model import *

app = FastAPI()

error_response = {'message': '''Something went wrong''', 'code': 401 }

# load data, models, collections

@app.get("/ping")
async def ping():
    return "Hello kakenhi ML"

@app.post("/get-institution")
async def get_nodes_keyword(req: KeywordQuery):
    try:
        print("/get-institution", req)
        return_data = [{'institution': 'Tokyo Metropolitan University',
                                'researcherProfiles': [{'firstName': 'CHIN WEIHONG',
                            'kakenhiID': '10876650'},
                        {'firstName': 'PETER GUENTERT', 'kakenhiID': '20392110'}]},
                        {'institution': 'Osaka University',
                        'researcherProfiles': [{'firstName': 'LI LIANGZHI', 'kakenhiID': '10875545'},
                        {'firstName': 'ORLOSKY JASON', 'kakenhiID': '10815111'},
                        {'firstName': 'Yoo Donghoon', 'kakenhiID': '20868541'},
                        {'firstName': 'Tamura Shinichi', 'kakenhiID': '30029540'},
                        {'firstName': 'SHIMIZU Masaki', 'kakenhiID': '20550304'},
                        {'firstName': 'MACPHERSON TOM', 'kakenhiID': '40821898'},
                        {'firstName': 'Nakagawa Ikuo', 'kakenhiID': '70647437'},
                        {'firstName': 'TAKAGI TATSUYA', 'kakenhiID': '80144517'},
                        {'firstName': 'TABATA Tomoji', 'kakenhiID': '10249873'}]},
                        {'institution': 'Osaka Prefecture University',
                        'researcherProfiles': [{'firstName': 'Roy Parthapratim',
                            'kakenhiID': '10837222'},
                        {'firstName': 'Chiang YiHan', 'kakenhiID': '10824196'}]},
                        {'institution': 'Okinawa Institute of Science and Technology Graduate University',
                        'researcherProfiles': [{'firstName': 'KATIC Jelena',
                            'kakenhiID': '10834947'},
                        {'firstName': 'Mikheyev Alexander', 'kakenhiID': '90601162'},
                        {'firstName': 'Shah Payal', 'kakenhiID': '30773220'}]},
                        {'institution': 'Kanazawa University',
                        'researcherProfiles': [{'firstName': 'Gary Ross', 'kakenhiID': '10708142'}]},
                        {'institution': 'Shinshu University',
                        'researcherProfiles': [{'firstName': 'Kimura Fumikazu',
                            'kakenhiID': '10621849'}]},
                        {'institution': 'Chubu University',
                        'researcherProfiles': [{'firstName': 'USAMI Hiroyasu',
                            'kakenhiID': '10847669'}]},
                        {'institution': 'Tokyo University of Agriculture and Technology',
                        'researcherProfiles': [{'firstName': 'NGUYEN TUAN CUONG',
                            'kakenhiID': '10814246'}]},
                        {'institution': 'The University of Tokyo',
                        'researcherProfiles': [{'firstName': 'KAWAZOE YOSHIMASA',
                            'kakenhiID': '10621477'},
                        {'firstName': 'WESTFECHTEL THOMAS', 'kakenhiID': '30896551'},
                        {'firstName': 'Sciazko Anna', 'kakenhiID': '30898945'},
                        {'firstName': 'Entzinger Jorg', 'kakenhiID': '60600327'},
                        {'firstName': 'Han Jiaxin', 'kakenhiID': '50791456'},
                        {'firstName': 'Berman Naomi', 'kakenhiID': '60814407'}]},
                        {'institution': 'The University of Aizu',
                        'researcherProfiles': [{'firstName': 'HEO Younghyon',
                            'kakenhiID': '10631476'},
                        {'firstName': 'MARKOV Konstantin', 'kakenhiID': '80394998'},
                        {'firstName': 'Liu Yong', 'kakenhiID': '60325967'},
                        {'firstName': 'Julian Villegas', 'kakenhiID': '50706281'},
                        {'firstName': 'Ilic Peter', 'kakenhiID': '10511503'}]},
                        {'institution': 'Japan Advanced Institute of Science and Technology',
                        'researcherProfiles': [{'firstName': 'Schwartzman Gregory',
                            'kakenhiID': '20815261'},
                        {'firstName': 'Nguyen Minh Le', 'kakenhiID': '30509401'}]},
                        {'institution': 'Research Institute for Humanity and Nature',
                        'researcherProfiles': [{'firstName': 'NguyenTien Hoang',
                            'kakenhiID': '20829379'}]},
                        {'institution': 'Tokyo Institute of Technology',
                        'researcherProfiles': [{'firstName': 'Patmonoaji Anindityo',
                            'kakenhiID': '20899265'}]},
                        {'institution': 'Institute of Physical and Chemical Research',
                        'researcherProfiles': [{'firstName': 'Tanaka Akinori',
                            'kakenhiID': '20791924'},
                        {'firstName': 'Zhao Qibin', 'kakenhiID': '30599618'},
                        {'firstName': 'AguilarLleyda David', 'kakenhiID': '40895653'},
                        {'firstName': 'Khan Emtiyaz', 'kakenhiID': '30858022'},
                        {'firstName': 'Gerofi Balazs', 'kakenhiID': '70633501'},
                        {'firstName': 'MESHGI Kourosh', 'kakenhiID': '80774835'},
                        {'firstName': 'Johansen Joshua', 'kakenhiID': '80625351'},
                        {'firstName': 'MIDDLETON STEVEN', 'kakenhiID': '60526797'}]},
                        {'institution': 'Doshisha University',
                        'researcherProfiles': [{'firstName': 'Yamamoto Seiichi',
                            'kakenhiID': '20374100'}]},
                        {'institution': 'Nagasaki University',
                        'researcherProfiles': [{'firstName': 'SUZUKI Ikumi',
                            'kakenhiID': '20637730'}]},
                        {'institution': 'Kyushu University',
                        'researcherProfiles': [{'firstName': 'ARIMURA Hidetaka',
                            'kakenhiID': '20287353'},
                        {'firstName': 'YAOKAI Feng', 'kakenhiID': '60363389'}]},
                        {'institution': 'Iwate Prefectural University',
                        'researcherProfiles': [{'firstName': 'FUJITA Hamido',
                            'kakenhiID': '30244990'}]},
                        {'institution': 'Kochi National College of Technology',
                        'researcherProfiles': [{'firstName': 'YAMAGUCHI Takumi',
                            'kakenhiID': '30230361'}]},
                        {'institution': 'Nagoya Bunri University',
                        'researcherProfiles': [{'firstName': 'Zhou Xinxin',
                            'kakenhiID': '30262645'}]},
                        {'institution': 'Nara Institute of Science and Technology',
                        'researcherProfiles': [{'firstName': 'AMIN MD. ALTAFUL',
                            'kakenhiID': '30379531'},
                        {'firstName': '', 'kakenhiID': '80823525'}]},
                        {'institution': 'Waseda University',
                        'researcherProfiles': [{'firstName': 'SAYAMA Hiroki',
                            'kakenhiID': '30345425'},
                        {'firstName': 'Veszteg Robert', 'kakenhiID': '30597753'},
                        {'firstName': 'Schmitz Alexander', 'kakenhiID': '30729455'},
                        {'firstName': 'Takarada Yudai', 'kakenhiID': '70367093'},
                        {'firstName': 'Parque Victor', 'kakenhiID': '50745221'}]},
                        {'institution': 'Nagoya University',
                        'researcherProfiles': [{'firstName': 'Otchia Christian',
                            'kakenhiID': '90761198'},
                        {'firstName': 'Abe Takashi', 'kakenhiID': '40645347'}]},
                        {'institution': 'Kyoto University',
                        'researcherProfiles': [{'firstName': 'NGUYEN Canh Hao',
                            'kakenhiID': '90626889'},
                        {'firstName': 'Wu Yang', 'kakenhiID': '30750559'},
                        {'firstName': 'Ishizu Koichi', 'kakenhiID': '50314224'}]},
                        {'institution': 'Aoyama Gakuin University',
                        'researcherProfiles': [{'firstName': 'ETCHUYA Kenji',
                            'kakenhiID': '90806499'}]},
                        {'institution': 'National Institute of Advanced Industrial Science and Technology',
                        'researcherProfiles': [{'firstName': 'Steven Phillips',
                            'kakenhiID': '90344209'},
                        {'firstName': 'Nobu, Masaru Konishi', 'kakenhiID': '40805644'},
                        {'firstName': 'LEBLAY Julien', 'kakenhiID': '70757377'}]},
                        {'institution': 'St. Marianna University School of Medicine',
                        'researcherProfiles': [{'firstName': '', 'kakenhiID': '30814628'}]},
                        {'institution': 'Ritsumeikan University',
                        'researcherProfiles': [{'firstName': 'Batjargal Biligsaikhan',
                            'kakenhiID': '30725396'},
                        {'firstName': 'Chandler Damon', 'kakenhiID': '70765495'}]},
                        {'institution': 'Japan Aerospace EXploration Agency',
                        'researcherProfiles': [{'firstName': 'andreevamori adriana',
                            'kakenhiID': '30747499'},
                        {'firstName': 'Tasker Elizabeth', 'kakenhiID': '40620373'},
                        {'firstName': 'Andrea Sansica', 'kakenhiID': '80867797'}]},
                        {'institution': 'Ibaraki University',
                        'researcherProfiles': [{'firstName': 'ZHANG CHENG',
                            'kakenhiID': '40755089'}]},
                        {'institution': 'Kanazawa Medical University',
                        'researcherProfiles': [{'firstName': 'Oda Hideto',
                            'kakenhiID': '40607967'}]},
                        {'institution': 'Hitotsubashi University',
                        'researcherProfiles': [{'firstName': 'Yamamoto Yuichi',
                            'kakenhiID': '40855178'}]},
                        {'institution': 'Kwansei Gakuin University',
                        'researcherProfiles': [{'firstName': 'Ishikawa Keichi',
                            'kakenhiID': '40259445'}]},
                        {'institution': 'Ryukoku University',
                        'researcherProfiles': [{'firstName': 'Lee Soo im',
                            'kakenhiID': '40288634'}]},
                        {'institution': 'National Institute of Information and Communications Technology',
                        'researcherProfiles': [{'firstName': 'Marie Benjamin',
                            'kakenhiID': '30869433'},
                        {'firstName': 'shen peng', 'kakenhiID': '80773118'},
                        {'firstName': 'Mano Hiroaki', 'kakenhiID': '10571581'}]},
                        {'institution': 'Advanced Telecommunications Research Institute International',
                        'researcherProfiles': [{'firstName': 'CALLAN Daniel',
                            'kakenhiID': '70374113'}]},
                        {'institution': 'Kitasato University',
                        'researcherProfiles': [{'firstName': 'Fukuda Hiroshi',
                            'kakenhiID': '70238484'}]},
                        {'institution': 'Chukyo University',
                        'researcherProfiles': [{'firstName': 'Hashimoto Manabu',
                            'kakenhiID': '70510832'}]},
                        {'institution': 'Kagawa University',
                        'researcherProfiles': [{'firstName': 'Nishinaka Miwa',
                            'kakenhiID': '70770741'}]},
                        {'institution': 'National Institute for Materials Science',
                        'researcherProfiles': [{'firstName': 'yoshikawa genki',
                            'kakenhiID': '70401172'},
                        {'firstName': 'WANG HONGXIN', 'kakenhiID': '60813756'}]},
                        {'institution': 'Tokyo Metropolitan Institute of Medical Science',
                        'researcherProfiles': [{'firstName': 'Horiuchi Junjiro',
                            'kakenhiID': '80392364'}]},
                        {'institution': 'National Institutes of Biomedical Innovation, Health and Nutrition',
                        'researcherProfiles': [{'firstName': 'Shandar Ahmad',
                            'kakenhiID': '80463298'}]},
                        {'institution': 'University of Tsukuba',
                        'researcherProfiles': [{'firstName': 'Shen Biao', 'kakenhiID': '80730811'}]},
                        {'institution': 'Kyorin University',
                        'researcherProfiles': [{'firstName': 'Malcolm Field',
                            'kakenhiID': '50381281'}]},
                        {'institution': 'Kio University',
                        'researcherProfiles': [{'firstName': 'UEJI Kayoko',
                            'kakenhiID': '50390208'}]},
                        {'institution': 'Kochi University of Technology',
                        'researcherProfiles': [{'firstName': 'Daniels Paul',
                            'kakenhiID': '50307245'}]},
                        {'institution': 'Kanto Gakuin University',
                        'researcherProfiles': [{'firstName': '', 'kakenhiID': '60323903'}]},
                        {'institution': 'Nagoya Institute of Technology',
                        'researcherProfiles': [{'firstName': '', 'kakenhiID': '50836616'}]},
                        {'institution': 'National Astronomical Observatory of Japan',
                        'researcherProfiles': [{'firstName': 'Wu Benjamin',
                            'kakenhiID': '50868718'}]},
                        {'institution': 'Hokkaido University',
                        'researcherProfiles': [{'firstName': 'Taylor Nicholas',
                            'kakenhiID': '50750824'}]},
                        {'institution': 'Kobe University',
                        'researcherProfiles': [{'firstName': 'Hascoet Tristan',
                            'kakenhiID': '60848448'}]},
                        {'institution': 'National Institute of Informatics',
                        'researcherProfiles': [{'firstName': '', 'kakenhiID': '60851730'}]},
                        {'institution': 'The University of Tokushima',
                        'researcherProfiles': [{'firstName': 'Yamamoto Tetsuya',
                            'kakenhiID': '60779396'}]},
                        {'institution': 'International Christian University',
                        'researcherProfiles': [{'firstName': 'PICHL Lukas',
                            'kakenhiID': '10343394'}]}]
        return {"data": return_data}
    except:
        traceback.print_exc()
        return error_response